name: build

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - alpine-x64
          # - alpine-arm64
          - bionic-x64
          - bionic-arm64
          - bionic-armhf
          - bionic-ppc64le
          - focal-riscv64
          # - focal-x64
          # - focal-arm64
          # - focal-armhf
          # - focal-ppc64le
          # - centos7-devtoolset8-arm32v7
          - centos7-devtoolset8-arm64
          - centos7-devtoolset8-ppc64le
          - centos7-devtoolset8-x64
          - bionic-devtoolset-arm32v7
          - bionic-devtoolset-ppc64le
          - focal-devtoolset-riscv64

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
        if: matrix.arch == 'centos7-devtoolset8-arm32v7' || matrix.arch == 'centos7-devtoolset8-arm64' || matrix.arch == 'centos7-devtoolset8-ppc64le' || matrix.arch == 'alpine-arm64' || matrix.arch == 'bionic-devtoolset-arm32v7' || matrix.arch == 'bionic-devtoolset-ppc64le' || matrix.arch == 'focal-devtoolset-riscv64' || matrix.arch == 'focal-riscv64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.arch }}
          file: ${{ matrix.arch }}/Dockerfile
          tags: vscodium/vscodium-linux-build-agent:${{ matrix.arch }}
          push: ${{ github.ref == 'refs/heads/master' }}
